package mock

// Port is a UN/LOCODE with its city. The same table is committed for Spark
// at spark/config/ports.csv (generated by `mocksources ports`).
type Port struct {
	Locode  string
	City    string
	Country string
	Aliases []string
}

// Origins are Indian ports; Destinations span the routes Indian exporters use.
var Origins = []Port{
	{"INMAA", "Chennai", "IN", []string{"Madras"}},
	{"INNSA", "Nhava Sheva", "IN", []string{"JNPT", "Jawaharlal Nehru"}},
	{"INMUN", "Mundra", "IN", nil},
	{"INCOK", "Cochin", "IN", []string{"Kochi"}},
	{"INVTZ", "Visakhapatnam", "IN", []string{"Vizag"}},
	{"INKRI", "Krishnapatnam", "IN", nil},
	{"INHZA", "Hazira", "IN", nil},
	{"INPAV", "Pipavav", "IN", nil},
	{"INTUT", "Tuticorin", "IN", []string{"Thoothukudi"}},
	{"INCCU", "Kolkata", "IN", []string{"Calcutta"}},
}

var Destinations = []Port{
	{"NLRTM", "Rotterdam", "NL", nil},
	{"DEHAM", "Hamburg", "DE", nil},
	{"BEANR", "Antwerp", "BE", []string{"Antwerpen"}},
	{"GBFXT", "Felixstowe", "GB", nil},
	{"GBSOU", "Southampton", "GB", nil},
	{"GBLGP", "London Gateway", "GB", nil},
	{"FRLEH", "Le Havre", "FR", nil},
	{"ESVLC", "Valencia", "ES", nil},
	{"ESBCN", "Barcelona", "ES", nil},
	{"ESALG", "Algeciras", "ES", nil},
	{"ITGOA", "Genoa", "IT", []string{"Genova"}},
	{"ITGIT", "Gioia Tauro", "IT", nil},
	{"ITSPE", "La Spezia", "IT", nil},
	{"GRPIR", "Piraeus", "GR", nil},
	{"TRAMR", "Ambarli", "TR", nil},
	{"TRMER", "Mersin", "TR", nil},
	{"EGPSD", "Port Said", "EG", nil},
	{"EGALY", "Alexandria", "EG", nil},
	{"MAPTM", "Tanger Med", "MA", nil},
	{"AEJEA", "Jebel Ali", "AE", nil},
	{"AEKLF", "Khalifa Port", "AE", []string{"Abu Dhabi"}},
	{"SAJED", "Jeddah", "SA", nil},
	{"SADMM", "Dammam", "SA", nil},
	{"OMSLL", "Salalah", "OM", nil},
	{"QAHMD", "Hamad", "QA", []string{"Doha"}},
	{"SGSIN", "Singapore", "SG", nil},
	{"MYPKG", "Port Klang", "MY", nil},
	{"MYTPP", "Tanjung Pelepas", "MY", nil},
	{"IDJKT", "Jakarta", "ID", []string{"Tanjung Priok"}},
	{"THLCH", "Laem Chabang", "TH", nil},
	{"VNSGN", "Ho Chi Minh City", "VN", []string{"Saigon", "Cat Lai"}},
	{"VNHPH", "Haiphong", "VN", nil},
	{"PHMNL", "Manila", "PH", nil},
	{"CNSHA", "Shanghai", "CN", nil},
	{"CNNGB", "Ningbo", "CN", nil},
	{"CNSZX", "Shenzhen", "CN", []string{"Yantian"}},
	{"CNTAO", "Qingdao", "CN", nil},
	{"HKHKG", "Hong Kong", "HK", nil},
	{"KRPUS", "Busan", "KR", []string{"Pusan"}},
	{"JPTYO", "Tokyo", "JP", nil},
	{"JPYOK", "Yokohama", "JP", nil},
	{"AUMEL", "Melbourne", "AU", nil},
	{"AUSYD", "Sydney", "AU", nil},
	{"USNYC", "New York", "US", []string{"NY/NJ", "Newark"}},
	{"USLAX", "Los Angeles", "US", nil},
	{"USSAV", "Savannah", "US", nil},
	{"USHOU", "Houston", "US", nil},
	{"CAVAN", "Vancouver", "CA", nil},
	{"BRSSZ", "Santos", "BR", nil},
	{"ZADUR", "Durban", "ZA", nil},
}
